### PR TITLE
Allow the version upgrade to be executed on a separate branch

### PR DESCRIPTION
**Pull request by dkaoster**
Hello, I'd like to be able to run this action on tag, but I'm getting an error of 

```
✖  fatal     Error: Command failed: git checkout 0.0.0 
error: pathspec '0.0.0' did not match any file(s) known to git.
```

I figured the easiest way is to add the ability to specify which (other) branch the version increment should be performed on.

### CODE REVIEW

**Comment by phips28** [comment]
how does your action config look like for that?

**Comment by dkaoster** [comment]
Ideally, I'd like to write something along the lines of:

```
name: Bump Package Version

on:
  push:
    tags:
      - '*'

jobs:
  update:
    name: Bump Package version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: master
      - uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag: 'true'
          branch: 'master'

```

My thinking is, I'd like to publish my package whenever a tag gets created, and then use this action to automatically increment the version in master.

**Comment by phips28** [comment]
ok looks cool. one thing that comes to my mind. is "branch" confusing? could be misleading with where to checkout?
do you have a better naming suggestion?
maybe "commit-to-branch"? also not that good 🙈

**Comment by dkaoster** [comment]
What do you think about `target-branch`?

**Comment by phips28** [comment]
I like that :) approved

**Comment by dkaoster** [comment]
@phips28 updated! Let me know if there's anything else I can do to test / document this.

Thanks for all your help 🙇

**Pull request merged**
