### PR TITLE
Remove runtime dependencies

### PR DESCRIPTION
**Pull request by melody-universe**
This PR removes all runtime dependencies from the library. This allows us to execute the node script without needing a Docker image, `node_modules`, or a bundled asset. This was the final (probably) effort resulting from a suggestion on #42.

See a working example of this PR [here](https://github.com/melody-universe/gh-action-bump-version/runs/3271650554?check_suite_focus=true).

### CODE REVIEW

**Comment by phips28** [comment]
@melody-universe this looks very promising :) I would prefer to merge this PR. As I understand it correctly, the other 2 PRs from you are obsolete if we merge this PR?
Before we can merge we should bump to 9.0.0 to avoid possible regressions. Or are you 100% sure all cases are working correctly?

**Comment by melody-universe** [comment]
You are correct, the other PR's would be obsolete if we merge this PR.

I haven't tested all use cases, but I'll build some tests real quick to make sure!

**Comment by melody-universe** [comment]
Just an update on this: I'm working on an automated end-to-end test suite to confirm 100% compatibility between the updated JavaScript action and the current Docker action. While the suite is expensive in terms of runtime, my hope is that it can be used for future pull requests to verify compatibility.

You can see the pull request as is working in my fork [here](https://github.com/melody-universe/gh-action-bump-version/pull/2).

It's automating commits to a test repo I've created [here](https://github.com/melody-universe/gh-action-bump-version-test/commits/main).

Still working on building the tests for the rest of the functionality, and right now this is testing the current version of gh-action-bump-version, but once it's done I'll merge it into the JavaScript action and *hopefully* we should remain at 100% passing!

At some point it might be worth considering building an integration test that proxies environment variable access as well as the `spawn`, `console.log`, and `console.error` functions, and I might do that in yet another PR, but the issue there is that it's testing the exact sequence of executions to various CLI's. That might be good to be 100% sure that the result of this action has not changed at all, but if we find a slightly more optimal way to call `git` for example, it will break that test, while passing the end-to-end test.

**Comment by joelcoxokc** [comment]
Hey can we please merge this!!!

This no longer works as it is outside the npm minor version

**Comment by joelcoxokc** [comment]
I meant to say.. Your entire github action no longer works as of this morning... 
8/24/2021 because npm set their minor version. and you are still referencing node 12 in your package

**Comment by phips28** [comment]
@joelcoxokc you can set your node version in your own action.yml.
#123

**Comment by joelcoxokc** [comment]
> @joelcoxokc you can set your node version in your own action.yml.
> #123

Thanks @phips28 for the speedy reply and fix

**Comment by melody-universe** [comment]
@phips28 Been busy with day job / life stuff. Working on getting the end-to-end testing suite up right now. I'm imagining we want to push that first and then see the test suite execute against this PR without any changes, since the end-to-end functionality should remain exactly the same.

**Pull request merged**
