### PR TITLE
Set working directory

### PR DESCRIPTION
**Pull request by MartijnBNG**
Set working directory according to the issue I created earlier today: https://github.com/phips28/gh-action-bump-version/issues/4

### CODE REVIEW

**Comment by phips28** [comment]
@MartijnBNG thx for your PR :) 
I improved it a little bit in #6 and merged, please test the master version.

**Comment by sammccants** [comment]
@phips28 just a heads up, this one works for me, but #6 does not. I believe it's because this one is setting GITHUB_WORKSPACE (which is then used by `tools.getPackageJSON()`) while #6 doesn't.

**Comment by phips28** [comment]
@sammccants can you create a PR to fix this?
I never use a custom package dir.

**Comment by sammccants** [comment]
@phips28 sure, here it is:
https://github.com/phips28/gh-action-bump-version/pull/13

**Pull request closed without merging**
