### PR TITLE
Update test to use null default

### PR DESCRIPTION
**Pull request by amccloud**
Thanks for creating this action. I noticed this test didn't quite match the label. I've been running into issues around the null case here and I suspect my `default: null` in yaml is not translating to null in js:

```
commit messages: [ 'fix\nundefined' ]
config words: {
  majorWords: [ 'major:', 'major(desktop):' ],
  minorWords: [ 'feat(desktop):', 'feature(desktop):' ],
  patchWords: [ 'patch:', 'hotfix:', 'fix(desktop):', 'fixes(desktop):' ],
  preReleaseWords: [ 'chore(pre):' ]
}
version action after first waterfall: 
version action after final decision: 
currentBranch: master
```

### CODE REVIEW

**Comment by phips28** [comment]
The tests are not really working, and therefore not useful.
https://github.com/phips28/gh-action-bump-version/issues/128

**Comment by phips28** [comment]
and yaml does not understand `null` as null. everything is converted to string from yaml to js.

**Comment by amccloud** [comment]
@phips28 exactly

Yaml doesn’t understand null and there is an explicit `version === null` at the end of this action. Because of that check and lack of null support the action throws an error if default is null or empty

I’ll update this PR with fix that go along with my test updates (even if test don’t work)

**Review by phips28 — APPROVED** [review]

**Comment by amccloud** [comment]
@phips28 thank you, I noticed my change to rename `pull-request.yml` is in this. You might not want that if the test aren't working. Sorry about that

**Pull request merged**
