### PR TITLE
Fix broken version-type rc

### PR DESCRIPTION
**Pull request by kevcube**
This was added in PR #176 but never worked for `prerelease` version type

### CODE REVIEW

**Comment by jamestalton** [comment]
Just ran into this. Glad to see a fix already available.

**Comment by jamestalton** [comment]
After picking up this change

```
version action after first waterfall: prerelease
version action after final decision: null
```

So it did not use prerelease. :(

@kevcube

**Comment by kevcube** [comment]
@jamestalton yes you still need prerelease wording in your commit. You can also change pre-release wording to be something like what patch wording is, I think `null`

check action.yml in this repo

**Comment by kevcube** [comment]
@jamestalton pr #176 seems kinda half-baked and my patch just fixes a very minor error with it.

**Comment by kevcube** [comment]
@jamestalton see #191

**Comment by sherifalaa55** [comment]
@phips28 haven't actually tried the rc... sorry about that

**Pull request merged**
